#!/usr/bin/env bash
# Regenerate background.css: a background image embedded as a data URI.
#
#   ./background.sh                    # uses background.jpg / .png / … if present
#   ./background.sh /path/to/photo.jpg
#   ./background.sh --source           # print the dropped-in image, if any
#
# A web page cannot load file:// images, so a local photo has to be inlined.
# The source is downscaled and re-encoded first — a full 2560px JPEG base64s to
# well over a megabyte, which makes the userstyle unpleasant to install.
set -euo pipefail
cd "$(dirname "$0")"

# The drop-in convention: a file called background.<ext> in this directory is
# picked up with no argument, and LOCAL=1 ./build.sh re-embeds it when it
# changes. Extensions are matched case-insensitively; sips reads all of these.
find_source() (
  shopt -s nullglob nocaseglob nocasematch
  matches=()
  for f in background.*; do
    case ${f##*.} in
      jpg|jpeg|png|heic|heif|webp|tif|tiff|gif|bmp) matches+=( "$f" ) ;;
    esac
  done
  case ${#matches[@]} in
    0) return 1 ;;
    1) printf '%s\n' "${matches[0]}" ;;
    *) printf 'background.sh: several dropped-in images, keep one: %s\n' "${matches[*]}" >&2
       return 2 ;;
  esac
)

if [ "${1:-}" = "--source" ]; then
  find_source
  exit $?
fi

if [ $# -gt 0 ]; then
  SRC=$1
  WIDTH=${2:-1920}
else
  SRC=$(find_source) && STATUS=0 || STATUS=$?
  if [ "$STATUS" = 2 ]; then exit 1; fi           # several candidates, already reported
  if [ "$STATUS" != 0 ]; then
    echo "usage: ./background.sh /path/to/image.jpg" >&2
    echo "   or: drop an image named background.jpg (or .png, .heic, …) here" >&2
    exit 1
  fi
  WIDTH=1920
fi

[ -f "$SRC" ] || { echo "background.sh: no such image: $SRC" >&2; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

# Keep the extension: sips sniffs content, but some formats it only opens when
# the name agrees.
EXT=${SRC##*/}; EXT=${EXT##*.}
cp "$SRC" "$TMP/in.$EXT"
sips --resampleWidth "$WIDTH" "$TMP/in.$EXT" --out "$TMP/out.$EXT" >/dev/null
sips -s format jpeg -s formatOptions 60 "$TMP/out.$EXT" --out "$TMP/final.jpg" >/dev/null

{
  echo "/* Generated by background.sh from $(basename "$SRC") — do not edit. */"
  echo ":root {"
  printf '  --gm-bg-image: url("data:image/jpeg;base64,%s");\n' "$(base64 -i "$TMP/final.jpg")"
  echo "}"
} > background.css

echo "background.css: $(( $(wc -c < background.css) / 1024 )) KB from $(( $(wc -c < "$TMP/final.jpg") / 1024 )) KB jpeg"
