#!/usr/bin/env bash
# Regenerate background.css: a background image embedded as a data URI.
#
#   ./background.sh /path/to/photo.jpg
#
# A web page cannot load file:// images, so a local photo has to be inlined.
# The source is downscaled and re-encoded first — a full 2560px JPEG base64s to
# well over a megabyte, which makes the userstyle unpleasant to install.
set -euo pipefail
cd "$(dirname "$0")"

SRC=${1:?usage: ./background.sh /path/to/image.jpg}
WIDTH=${2:-1920}
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

cp "$SRC" "$TMP/in.jpg"
sips --resampleWidth "$WIDTH" "$TMP/in.jpg" --out "$TMP/out.jpg" >/dev/null
sips -s format jpeg -s formatOptions 60 "$TMP/out.jpg" --out "$TMP/final.jpg" >/dev/null

{
  echo "/* Generated by background.sh from $(basename "$SRC") — do not edit. */"
  echo ":root {"
  printf '  --gm-bg-image: url("data:image/jpeg;base64,%s");\n' "$(base64 -i "$TMP/final.jpg")"
  echo "}"
} > background.css

echo "background.css: $(( $(wc -c < background.css) / 1024 )) KB from $(( $(wc -c < "$TMP/final.jpg") / 1024 )) KB jpeg"
