#!/usr/bin/env bash
# Regenerate fonts.css: Gmail's typefaces embedded as base64 data URIs.
#
# Why embedded rather than @import from fonts.googleapis.com: an extension's
# injected stylesheet is still subject to the PAGE's Content-Security-Policy,
# so a remote font-src can be blocked with no visible error — the text just
# silently falls back to Helvetica. A data: URI carries no network fetch.
# Only the latin subsets are pulled, to keep the file reasonable.
set -euo pipefail
cd "$(dirname "$0")"

# Google Sans / Google Sans Text are Google-restricted fonts: fine to use on
# your own machine, not something to redistribute in a public repo. They are
# only fetched with --google-sans, and the result is gitignored.
# Plain run writes fonts.css (committed, Roboto + Material Symbols).
# --google-sans writes fonts.local.css, which is gitignored, so the two builds
# never overwrite each other.
WANT_GOOGLE_SANS=0
OUT=fonts.css
if [ "${1:-}" = "--google-sans" ]; then WANT_GOOGLE_SANS=1; OUT=fonts.local.css; fi
export OUT

UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
API="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
if [ "$WANT_GOOGLE_SANS" = "1" ]; then
  API="https://fonts.googleapis.com/css2?family=Google+Sans:wght@400;500;700&family=Google+Sans+Text:wght@400;500;700&family=Roboto:wght@400;500;700&display=swap"
fi

# Gmail's folder icons are Material Symbols ligatures. Only the handful of
# glyphs the folder list needs is requested, so this stays a few KB.
ICONS="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0&icon_names=inbox,send,draft,drafts,delete,report,archive,star,schedule,label,folder,outbox,history,group"

curl -s -A "$UA" "$API"   > /tmp/gmailify-fonts-src.css
curl -s -A "$UA" "$ICONS" > /tmp/gmailify-icons-src.css

python3 - <<'PY'
import base64, re, urllib.request

src = open('/tmp/gmailify-fonts-src.css').read()
# Blocks are preceded by a /* subset */ comment; keep only latin.
blocks = re.split(r'/\*\s*([a-z0-9-]+)\s*\*/', src)
out = ['/* Generated by fonts.sh — do not edit. Gmail\'s typefaces, embedded as',
       '   data URIs so no network fetch and no page CSP can defeat them. */', '']
kept = 0
for i in range(1, len(blocks) - 1, 2):
    subset, css = blocks[i], blocks[i + 1]
    if subset != 'latin':
        continue
    m = re.search(r'src:\s*url\((https://fonts\.gstatic\.com/[^)]+)\)', css)
    fam = re.search(r"font-family:\s*'([^']+)'", css)
    wgt = re.search(r'font-weight:\s*(\d+)', css)
    if not (m and fam and wgt):
        continue
    data = urllib.request.urlopen(m.group(1)).read()
    b64 = base64.b64encode(data).decode()
    out.append(f"""@font-face {{
  font-family: '{fam.group(1)}';
  font-style: normal;
  font-weight: {wgt.group(1)};
  font-display: swap;
  src: url(data:font/woff2;base64,{b64}) format('woff2');
}}""")
    kept += 1
    print(f"  embedded {fam.group(1)} {wgt.group(1)}  ({len(data)//1024} KB)")

# Material Symbols: one unsubsetted @font-face, no subset comments.
icons = open('/tmp/gmailify-icons-src.css').read()
m = re.search(r'src:\s*url\((https://fonts\.gstatic\.com/[^)]+)\)', icons)
if m:
    data = urllib.request.urlopen(m.group(1)).read()
    out.append(f"""@font-face {{
  font-family: 'Material Symbols Outlined';
  font-style: normal;
  font-weight: 400;
  font-display: block;
  src: url(data:font/woff2;base64,{base64.b64encode(data).decode()}) format('woff2');
}}""")
    kept += 1
    print(f"  embedded Material Symbols Outlined  ({len(data)//1024} KB)")

open(__import__('os').environ.get('OUT','fonts.css'), 'w').write('\n'.join(out) + '\n')
print(f"{__import__('os').environ.get('OUT','fonts.css')}: {kept} faces")
PY
