"""Turn a `quiz.src.json` document into Typst: the blank quiz and the key.

Both documents are generated from one string, differing in a single boolean.
That is deliberate.  redpen cuts its zones out of the *blank*, and a key whose
boxes had drifted even slightly would mis-crop every scan while looking
perfectly fine to read -- the failure the README warns about at length.  Here
the two files cannot drift, because there is only one layout.
"""
import os, re

from . import quizdoc
from .quizdoc import LETTERS, part_id, zone_id

LIB = "quizlib.typ"

HEADER = """// Generated by redpen from {src}.
//
// Do not edit: `redpen build` overwrites this file.  Edit the quiz in the
// composer, or in {src} directly, and build again.
"""


def _s(v):
    """A Typst string literal."""
    return '"' + str(v).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _c(v, indent=0, empty="none"):
    """A Typst content literal.  The text is markup: $math$, *bold*, _italic_.

    `empty` is what an empty field becomes: `none` for an optional argument,
    `[]` for the trailing content one, which must always be given.
    """
    text = quizdoc._atref(str(v).strip())
    if not text:
        return empty
    pad = " " * indent
    # A field ending in a backslash is a Typst line break, and would otherwise
    # escape the bracket that closes this literal.
    tail = "\n" + pad if text.endswith("\\") else ""
    if "\n" in text:
        body = ("\n" + pad + "  ").join(l.strip() for l in text.splitlines())
        return "[\n" + pad + "  " + body + "\n" + pad + "]"
    return "[" + text + tail + "]"


def _num(x):
    x = float(x)
    return str(int(x)) if x == int(x) else str(x)


def _box(pi, qi, q, b):
    """One answer box, as the dictionary `answer-box` expects."""
    fields = [
        f"id: {_s(zone_id(pi, qi, q, b))}",
        f"label: {_s(b['label'])}",
        f"w: {b['w']}", f"h: {b['h']}",
    ]
    if b["kind"] == "sketch":
        fields.append("tall: true")
        fields.append(f"kind: {_s('sketch')}")
    ans = b.get("raw") or b.get("answer", "")
    if str(ans).strip():
        fields.append(f"answer: {_c(ans)}")
    return "(" + ", ".join(fields) + ")"


def _part(pi, qi, q, lbl=None, body=None):
    """One sub-part.  `lbl` of None drops the letter, for an answers-only
    problem whose body is the problem statement."""
    pid = part_id(pi, qi)
    boxes = ", ".join(_box(pi, qi, q, b) for b in q["boxes"])
    if len(q["boxes"]) == 1:
        boxes += ","                      # a one-element Typst array needs it
    out = [f'      part({_s(lbl) if lbl else "none"}, id: {_s(pid)}, key: KEY,']
    out.append(f"        boxes: ({boxes}),")
    lines = [l.strip() for l in q["solution"] if str(l).strip()]
    if q.get("raw"):
        lines.append(q["raw"])
    if lines:
        # A trailing backslash is Typst's line break, which is how the key
        # sets one step of working per line.  Named `sol`, not `body`: `body`
        # is the argument holding the question.
        sol = ("\\\n          ").join(lines)
        out.append("        solution: [\n          " + sol + "\n        ],")
    # The body is a positional argument, so an unwritten question is `[]`,
    # not `none`: a sub-part added in the composer must still compile.
    out.append("      )" + _c(q["question"] if body is None else body,
                               indent=6, empty="[]") + ",")
    return "\n".join(out)


def _problem(pi, p):
    # An answers-only problem has no letters and no separate question: the
    # statement itself goes in the sub-part's body, so the answer boxes line
    # up beside it rather than beside an empty column.
    direct = p.get("direct") and len(p["parts"]) == 1
    head = [f"#problem({pi},"]
    if p["title"]:
        head.append(f"  title: {_c(p['title'])},")
    if p["points"]:
        head.append(f"  pts: {_num(p['points'])},")
    if p["stem"] and not direct:
        head.append(f"  stem: {_c(p['stem'], indent=2)},")
    # Every sub-part on the page claims an equal share of what is left of it,
    # and `gap` is the nudge off equal -- 1.5 is half as much room again as
    # its neighbours.  Marks deliberately do not enter into it: a question
    # worth more is not automatically a question that needs more paper, and
    # tying the two together made the room impossible to set by hand.
    gaps = [_num(round(float(q["gap"]), 3)) for q in p["parts"]]
    head.append("  gaps: (" + ", ".join(gaps) + (",)" if len(gaps) == 1 else ")") + ",")
    head.append("  parts: (")
    for qi, q in enumerate(p["parts"]):
        head.append(_part(pi, qi, q,
                          lbl=None if direct else LETTERS[qi],
                          body=p["stem"] if direct else None))
    head.append("  ),")
    head.append(")")
    return "\n".join(head)


def emit(doc, key=False, src="quiz.src.json"):
    """The whole document, as Typst source."""
    probs = quizdoc.live(doc)          # archived problems are simply not here
    pages = quizdoc.pages_of(doc)
    # Problems sharing a page divide what is left of it evenly, sub-part by
    # sub-part, so a page laid out without a single hand-set number is already
    # the evenly spaced one.
    by_page = {}
    for n, pg in enumerate(pages):
        by_page.setdefault(pg, []).append(n)

    out = [HEADER.format(src=src)]
    out.append(f'#import "{LIB}": *')
    out.append(f"#let KEY = {'true' if key else 'false'}")
    out.append("")
    if doc.get("preamble", "").strip():
        # Verbatim, for the things a form has no business trying to hold: a
        # hand-drawn graph, a custom table, a one-off helper.
        out.append("// ---- from the quiz's own preamble ----")
        out.append(doc["preamble"].strip())
        out.append("")
    out.append("#show: quiz-doc.with(")
    out.append(f"  title: {_s(doc['title'])},")
    out.append("  key: KEY,")
    if doc.get("note"):
        out.append(f"  note: {_c(doc['note'], indent=2)},")
    out.append(")")
    out.append("")

    for i, pg in enumerate(sorted(by_page)):
        if i:
            out.append("#pagebreak()")
            out.append("")
        idx = by_page[pg]
        out.append("#quiz-page[")
        for n in idx:
            out.append(_problem(n + 1, probs[n]))
        out.append("]")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def write(doc, outdir=None, stem=None, src=None):
    """Write quizlib.typ, the quiz and the key.  Returns their paths."""
    outdir = outdir or doc["_dir"]
    src = src or os.path.basename(doc.get("_path", "quiz.src.json"))
    stem = stem or re.sub(r"\.src\.json$|\.json$", "", src) or "quiz"
    os.makedirs(outdir, exist_ok=True)

    lib_src = os.path.join(os.path.dirname(os.path.abspath(__file__)), LIB)
    lib_dst = os.path.join(outdir, LIB)
    with open(lib_src) as f:
        lib = f.read()
    # Rewritten every build, so a quiz folder always carries the library that
    # produced it and stays compilable on its own.
    with open(lib_dst, "w") as f:
        f.write(lib)

    quiz = os.path.join(outdir, f"{stem}.typ")
    keyf = os.path.join(outdir, f"{stem}-key.typ")
    with open(quiz, "w") as f:
        f.write(emit(doc, key=False, src=src))
    with open(keyf, "w") as f:
        f.write(emit(doc, key=True, src=src))
    return {"lib": lib_dst, "quiz": quiz, "key": keyf, "stem": stem}
